name: antibet
description: Diário de Apostas e Ferramenta de Análise. MVP funcional da Inovexa Software.

# Previne o acesso a arquivos de código fonte.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de Estado
  flutter_riverpod: ^3.0.3 

  # Comunicação com API (Rede)
  dio: ^5.4.0
  
  # Modelagem de Dados e Serialização
  json_annotation: ^4.8.1

  # Persistência local (Usado para simular o armazenamento seguro do Token)
  shared_preferences: ^2.2.2 

  # UX / Ícones
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Ferramentas de Teste e Mocks
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

  # Ferramentas de Build para Serialização JSON
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Ativos (se houvesse imagens ou fontes personalizadas)
  # assets:
  #   - assets/