name: antibet
description: Projeto mobile para gerenciamento financeiro pessoal.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- DEPENDÊNCIAS ATUALIZADAS (2025) ---
  # A versão 0.19.0 do intl é OBRIGATÓRIA para o seu Flutter atual
  intl: 0.20.2 
  
  cupertino_icons: ^1.0.6
  dio: ^5.4.0 
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Geradores
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  
  # Ícones
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo/

# Configuração de Ícones
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo/ic_launcher.png"
  min_sdk_android: 21